/* Hildana. M
 * CDCalculator_U2_A6.java
 * This program shows the number of years it will take  
 * to get the desired cd value 
 * March/29/2018
 */

/**
 *
 * @author himel9675
 */
public class CDCalculator_U2_A6 extends javax.swing.JFrame {

    /**
     * Creates new form CDCalculator_U2_A6
     */
    public CDCalculator_U2_A6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelInvestment = new javax.swing.JLabel();
        labelInterest = new javax.swing.JLabel();
        labelEndingVal = new javax.swing.JLabel();
        textInvestment = new javax.swing.JTextField();
        textInterest = new javax.swing.JTextField();
        textEndingVal = new javax.swing.JTextField();
        buttonCalculate = new javax.swing.JButton();
        labelNumYear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitle.setText("CD Calculator");

        labelInvestment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelInvestment.setText("Enter initial investments ($):");

        labelInterest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelInterest.setText("Enter anual interest rate (%):");

        labelEndingVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEndingVal.setText("Enter ending value ($):");

        textInvestment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textInvestment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInvestmentActionPerformed(evt);
            }
        });

        textInterest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInterestActionPerformed(evt);
            }
        });

        textEndingVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textEndingVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEndingValActionPerformed(evt);
            }
        });

        buttonCalculate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        labelNumYear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNumYear.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(labelTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelInterest)
                                    .addComponent(labelEndingVal)
                                    .addComponent(labelInvestment))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textEndingVal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonCalculate, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addComponent(labelNumYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEndingVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEndingVal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCalculate)
                .addGap(18, 18, 18)
                .addComponent(labelNumYear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textInvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInvestmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInvestmentActionPerformed

    private void textInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInterestActionPerformed

    private void textEndingValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEndingValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEndingValActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        
        //declaring value 
        double investVal, interest, endVal, cdVal;
        int numVal; 
        
        //retrieve what the individual entered in each section 
        investVal = Double.parseDouble(textInvestment.getText());
        interest = Double.parseDouble(textInterest.getText());
        endVal = Double.parseDouble(textEndingVal.getText());
      
        //initial cd value 
        cdVal = investVal;
        
        //couter 
        numVal =  0;
        
        while ( cdVal <= endVal) //if the cd value is greater or equal to the end value, then...
        {
           numVal += 1; //every time program executes, add an increment of 1 
           cdVal = cdVal + (cdVal*(interest/100)); //cd Value formula 
           labelNumYear.setText("The number of years required is " + numVal); 
        }        
        
    }//GEN-LAST:event_buttonCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CDCalculator_U2_A6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CDCalculator_U2_A6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CDCalculator_U2_A6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CDCalculator_U2_A6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CDCalculator_U2_A6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEndingVal;
    private javax.swing.JLabel labelInterest;
    private javax.swing.JLabel labelInvestment;
    private javax.swing.JLabel labelNumYear;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textEndingVal;
    private javax.swing.JTextField textInterest;
    private javax.swing.JTextField textInvestment;
    // End of variables declaration//GEN-END:variables
}
